language: ruby

rvm:
  - 2.3.0

bundler_args: --without development --deployment

cache: bundler

script:
  - bundle exec rake test

deploy:
  provider: heroku
  api_key:
    secure: YLHOaZPgNkPUmxuD0Jr0oUmxpl0NMOP0PYV07OcaEi/K8Pc+l/xKne7CYCs2Hz3bxrzR4bAc7HYLRxuIAwFwVY/BHtqQbCl9dfWC56Mntx9w28AR76GeTu4a9Ckz8DL/U30YzXI+OGfwIyhMQ6F3smKECif00NP/Y4PyQGrus43l8TFC3oFHpd3RvQ4yyjn6/gu5xLmKN83SxLgNT4eHE3UQiIHC9xevUaWtSPb9ZMxvWbRAbu47YFEJg5lW9vTZdSkYYEVrpGjrZVhtuq+1eLqeJ/eESeO+Zs57e1+vdWhOGKHUQ3DITrxqv9MdPwUDHhQUbRnOpb58cQULVnEYg4uq49XNXDVebDz0+XPuYc8jE5TsT8XIOiY+0jajbIumRkPe6bf868+PG5es639HDqvPtd//bLstRJr8h3zPWVTMdaA3hB6oBgL+pAk2o5BolqOxylYI1B6twf4X/V82ivcpQPvUlwCMR8xZiEHUpUTGCnNHE+RJ99BhAaYtpWezopBc0sm8io22rdb2vZzE3FBd0+8Nd47ifytrP66O3aJyIgoFBAJZuZpyUFSQZcUtmHTIEOiBcSj9Ogs5JsMtfpLEMVnRcZ5mXs7T+N77kqA+dWvklIxCCgL3ywZI0A6XdJfmpfossSAB1FJ/v/AqZYBB9jljzBvrXf4GuvIu50o=
